### ISSUE TITLE
I Hate to Do This Again, But

### ISSUE THREAD

**Issue by captainbob32** [GabubuAvailable/wads-by-gabubu#10]
I Only Had a Guilded Account. Guilded is Discord, But Actually Good.

(I Had Think Before Posting This and I Had Think "Oh, Come on, Mind! I Don't Wanna Be Annoying Again!", But my Mind had Forced me to Post This)

I'm Closing for Now. Bye!

-Your Fan, captainbob321

**Comment by GabubuAvailable** [comment]
You don't even reply on Discord and you say you have Guilded account? What the f$ck?

**Comment by ghost** [comment]
Oh No, What Have I Done?! I Don't Have Discord!

**Comment by ghost** [comment]
Maybe I Should Beat Myself Up!

**Comment by GabubuAvailable** [comment]
>Oh No, What Have I Done?! I Don't Have Discord!

OH YEAH? THEN WHO captainbob321#4835 IS???

**Comment by GabubuAvailable** [comment]
Ok. You are too annoying...

**Comment by ghost** [comment]
Um, Me Maybe?

I'm Sorry, Man. I Won't Do It Again
