### ISSUE TITLE
[New Forwarder] Some-YAWMM-Mod

### ISSUE THREAD

**Issue by DraconicNEO** [GabubuAvailable/wads-by-gabubu#2]
I have an idea for another app you could make a forwarder to, [Some-YAWMM-Mod](https://github.com/FIX94/Some-YAWMM-Mod). I haven't seen any forwarder to this app yet.

**Comment by GabubuAvailable** [comment]
https://github.com/GabubuAvailable/WADs-by-Gabubu/releases/download/vWii/YAWMM.-.YAWM.-.vWii.wad
I made it. :D
I hope you like it ;)
