### ISSUE TITLE
Dolphin WiiLink24 SPD not working.

### ISSUE THREAD

**Issue by weeniemount** [GabubuAvailable/wads-by-gabubu#7]
When i go to the channel, when i select something to edit and press done it spits out a error on the console and goes back. Any ideas?

**Comment by GabubuAvailable** [comment]
Can you send a screenshot of that error?

**Comment by Damaj301damaj-lol** [comment]
AH, this is wiilink24's fault(not really :P) because the done button attempts to return to either loader or the digicam channel(not sure), but the loader being the system menu, it crashes.

**Comment by GabubuAvailable** [comment]
Yeah makes sense. Make sure you have the DigiCam Channel installed on Dolphin in order to work when you press "done".
