### ISSUE TITLE
I Don't Wanna do This, But

### ISSUE THREAD

**Issue by captainbob32** [GabubuAvailable/wads-by-gabubu#9]
I'll Try to Stop Being so Weird and Think Before Posting Something. Before I Posted This "Thing", I Was Thinking: "Wait, What if He will Get Angry at Me?" But Then, I Was Like "Eh, Forget It" So I'll Stop for Now, Never Asked for a Font Again, Never Misunderstood/Thought XFlak is Dead and Be Inactive to Watch YouTube Videos.

-Your Fan, captainbob321 (Yes, I'm a Fan)

**Comment by ghost** [comment]
Also, I Followed You as a Fan

**Comment by ghost** [comment]
and Watched and Starred This Project as a Fan (OK, I'll be Inactive for Reals)

**Comment by ghost** [comment]
I'll Close this Thing Now

**Comment by ghost** [comment]
I Know I Said I Would Stop, But I Felt Like I Really Need to Get This Said Here. I Wish I Could PM You for a Font, But Whenever I Go into your GBATemp Profile, It Just Says "Oops! We ran into some problems. This member limits who may view their full profile."

**Comment by GabubuAvailable** [comment]
Bro... that's another reason of being so weird... I see, you can't PM me on GBATemp but you can DM me on Discord, BUT NOT HERE OH COME ON...

**Comment by ghost** [comment]
Yeah
